name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip
      - name: Unzip project
        run: unzip -o smart_recipe_app_github_ready.zip -d project
      - name: Ensure Gradle wrapper
        run: |
          cd project
          if [ ! -f gradlew ]; then
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.2.1
            gradle wrapper --gradle-version 8.2.1
          fi
          chmod +x gradlew
      - name: Build Debug APK
        run: cd project && ./gradlew --no-daemon clean assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: SmartRecipeApp-Debug
          path: project/app/build/outputs/apk/debug/*.apk
