name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip project
        run: unzip -o smart_recipe_app_github_ready.zip -d project

      - name: Detect Gradle project root (settings.gradle)
        id: detect
        shell: bash
        run: |
          set -e
          ROOT_FILE=$(find project -maxdepth 3 -name "settings.gradle" -print -quit)
          if [ -z "$ROOT_FILE" ]; then
            echo "settings.gradle not found."
            find project -maxdepth 3 -print
            exit 1
          fi
          ROOT_DIR=$(dirname "$ROOT_FILE")
          echo "PROJECT_DIR=$ROOT_DIR" >> $GITHUB_ENV
          echo "Project root: $ROOT_DIR"

      - name: Ensure Gradle wrapper
        shell: bash
        run: |
          if [ ! -f "$PROJECT_DIR/gradlew" ]; then
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.2.1
            (cd "$PROJECT_DIR" && gradle wrapper --gradle-version 8.2.1)
          fi
          chmod +x "$PROJECT_DIR/gradlew"

      - name: Build Debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: ./gradlew --no-daemon clean assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: SmartRecipeApp-Debug
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
