name: Build Android APK from ZIP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # اگر اسم فایل ZIP شما فرق دارد، این خط را مطابق اسم فایل خودتان تغییر دهید
      - name: Unzip project
        run: unzip -o smart_recipe_app_fixed.zip -d project

      - name: Install Gradle via SDKMAN and create wrapper
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.6
          cd project
          gradle wrapper --gradle-version 8.6
          chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: project
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartRecipeApp-Debug
          path: project/app/build/outputs/apk/debug/*.apk
